name: network-operations
functions:
- name: aggregate
  spec:
    kind: job
    metadata:
      name: aggregate
      tag: ''
      hash: 06454ac064876899b23bc9e3128f53c84b1c2ba2
      project: network-operations
    spec:
      command: /User/demo-network-operations/src/aggregate.py
      args: []
      image: ''
      env:
      - name: V3IO_API
        value: ''
      - name: V3IO_USERNAME
        value: ''
      - name: V3IO_ACCESS_KEY
        value: ''
      description: ''
      build:
        source: ./
        commands: []
        code_origin: http://github.com/zilbermanor/demo-network-operations#0b8008a76e97b7806250ecf029094b597dd94507
- name: describe
  spec:
    kind: job
    metadata:
      name: describe
      tag: ''
      hash: 88b2063f5e23b0d76f76d72a65bdc152916272a5
      project: network-operations
    spec:
      command: ''
      args: []
      image: yjbds/mlrun-ml:v0.4.5
      env:
      - name: V3IO_API
        value: ''
      - name: V3IO_USERNAME
        value: ''
      - name: V3IO_ACCESS_KEY
        value: ''
      description: ''
      build:
        functionSourceCode: IyBDb3B5cmlnaHQgMjAxOCBJZ3VhemlvCiMKIyBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2UiKTsKIyB5b3UgbWF5IG5vdCB1c2UgdGhpcyBmaWxlIGV4Y2VwdCBpbiBjb21wbGlhbmNlIHdpdGggdGhlIExpY2Vuc2UuCiMgWW91IG1heSBvYnRhaW4gYSBjb3B5IG9mIHRoZSBMaWNlbnNlIGF0CiMKIyAgIGh0dHA6Ly93d3cuYXBhY2hlLm9yZy9saWNlbnNlcy9MSUNFTlNFLTIuMAojCiMgVW5sZXNzIHJlcXVpcmVkIGJ5IGFwcGxpY2FibGUgbGF3IG9yIGFncmVlZCB0byBpbiB3cml0aW5nLCBzb2Z0d2FyZQojIGRpc3RyaWJ1dGVkIHVuZGVyIHRoZSBMaWNlbnNlIGlzIGRpc3RyaWJ1dGVkIG9uIGFuICJBUyBJUyIgQkFTSVMsCiMgV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJVElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzIG9yIGltcGxpZWQuCiMgU2VlIHRoZSBMaWNlbnNlIGZvciB0aGUgc3BlY2lmaWMgbGFuZ3VhZ2UgZ292ZXJuaW5nIHBlcm1pc3Npb25zIGFuZAojIGxpbWl0YXRpb25zIHVuZGVyIHRoZSBMaWNlbnNlLgppbXBvcnQgb3MKaW1wb3J0IG51bXB5IGFzIG5wCmltcG9ydCBwYW5kYXMgYXMgcGQKaW1wb3J0IG1hdHBsb3RsaWIucHlwbG90IGFzIHBsdAppbXBvcnQgc2VhYm9ybiBhcyBzbnMKCmZyb20gbWxydW4uZXhlY3V0aW9uIGltcG9ydCBNTENsaWVudEN0eApmcm9tIG1scnVuLmRhdGFzdG9yZSBpbXBvcnQgRGF0YUl0ZW0KZnJvbSBtbHJ1bi5hcnRpZmFjdHMgaW1wb3J0IFBsb3RBcnRpZmFjdCwgVGFibGVBcnRpZmFjdAoKZnJvbSB5ZWxsb3dicmljay50YXJnZXQgaW1wb3J0IENsYXNzQmFsYW5jZQpmcm9tIHNrbGVhcm4ucHJlcHJvY2Vzc2luZyBpbXBvcnQgU3RhbmRhcmRTY2FsZXIKCmZyb20gdHlwaW5nIGltcG9ydCBJTywgQW55U3RyLCBVbmlvbiwgTGlzdCwgT3B0aW9uYWwKCnBkLnNldF9vcHRpb24oImRpc3BsYXkuZmxvYXRfZm9ybWF0IiwgbGFtYmRhIHg6ICIlLjJmIiAlIHgpCgpkZWYgX2djZl9jbGVhcihwbHQpOgogICAgcGx0LmNsYSgpCiAgICBwbHQuY2xmKCkKICAgIHBsdC5jbG9zZSgpIAoKZGVmIHRhYmxlX3N1bW1hcnkoCiAgICBjb250ZXh0OiBNTENsaWVudEN0eCwKICAgIHRhYmxlOiBVbmlvbltEYXRhSXRlbSwgc3RyXSwKICAgIGxhYmVsX2NvbHVtbjogc3RyLAogICAgY2xhc3NfbGFiZWxzOiBMaXN0W3N0cl0sCiAgICBrZXk6IHN0ciA9ICJ0YWJsZS1zdW1tYXJ5IiwKKSAtPiBOb25lOgogICAgIiIiU3VtbWFyaXplIGEgdGFibGUKCiAgICBUT0RPOiBtZXJnZSB3aXRoIGRhc2sgdmVyc2lvbgoKICAgIDpwYXJhbSBjb250ZXh0OiAgICAgICAgIHRoZSBmdW5jdGlvbiBjb250ZXh0CiAgICA6cGFyYW0gdGFibGU6ICAgICAgICAgICBwYW5kYXMgZGF0YWZyYW1lCiAgICA6cGFyYW0ga2V5OiAgICAgICAgICAgICBrZXkgb2YgdGFibGUgc3VtbWFyeSBpbiBhcnRpZmFjdCBzdG9yZQogICAgIiIiCiAgICBfZ2NmX2NsZWFyKHBsdCkKICAgIAogICAgYmFzZV9wYXRoID0gY29udGV4dC5hcnRpZmFjdF9wYXRoCiAgICBvcy5tYWtlZGlycyhiYXNlX3BhdGgsIGV4aXN0X29rPVRydWUpCiAgICBvcy5tYWtlZGlycyhiYXNlX3BhdGgrIi9wbG90cyIsIGV4aXN0X29rPVRydWUpCiAgICAKICAgIHRhYmxlID0gcGQucmVhZF9wYXJxdWV0KHN0cih0YWJsZSkpCiAgICBoZWFkZXIgPSB0YWJsZS5jb2x1bW5zLnZhbHVlcwogICAgCiAgICAjIHNldCBhIGZldyB2YWx1ZXMgdG8gTmFOIGp1c3QgZm9yIHRlc3RpbmcKICAgIHRhYmxlLmlsb2NbMTAwMDM6MTAwMTAsIDI6N10gPSBucC5OYU4KICAgIAogICAgIyBkZXNjcmliZSB0YWJsZQogICAgc3VtdGJsID0gdGFibGUuZGVzY3JpYmUoKQogICAgc3VtdGJsID0gc3VtdGJsLmFwcGVuZChsZW4odGFibGUuaW5kZXgpLXRhYmxlLmNvdW50KCksIGlnbm9yZV9pbmRleD1UcnVlKQogICAgc3VtdGJsLmluc2VydCgwLCAibWV0cmljIiwgWyJjb3VudCIsICJtZWFuIiwgInN0ZCIsICJtaW4iLCIyNSUiLCAiNTAlIiwgIjc1JSIsICJtYXgiLCAibmFucyJdKQogICAgCiAgICBzdW10YmwudG9fY3N2KG9zLnBhdGguam9pbihiYXNlX3BhdGgsIGtleSsiLmNzdiIpLCBpbmRleD1GYWxzZSkKICAgIGNvbnRleHQubG9nX2FydGlmYWN0KGtleSwgbG9jYWxfcGF0aD1rZXkrIi5jc3YiKQoKICAgICMgcGxvdCBjbGFzcyBiYWxhbmNlLCByZWNvcmQgcmVsYXRpdmUgY2xhc3Mgd2VpZ2h0CiAgICBfZ2NmX2NsZWFyKHBsdCkKICAgIAogICAgbGFiZWxzID0gdGFibGUucG9wKGxhYmVsX2NvbHVtbikKICAgIGNsYXNzX2JhbGFuY2VfbW9kZWwgPSBDbGFzc0JhbGFuY2UobGFiZWxzPWNsYXNzX2xhYmVscykKICAgIGNsYXNzX2JhbGFuY2VfbW9kZWwuZml0KGxhYmVscykKICAgIAogICAgc2NhbGVfcG9zX3dlaWdodCA9IGNsYXNzX2JhbGFuY2VfbW9kZWwuc3VwcG9ydF9bMF0vY2xhc3NfYmFsYW5jZV9tb2RlbC5zdXBwb3J0X1sxXQogICAgY29udGV4dC5sb2dfYXJ0aWZhY3QoInNjYWxlX3Bvc193ZWlnaHQiLCBmIntzY2FsZV9wb3Nfd2VpZ2h0OjAuMmZ9IikKCiAgICBjbGFzc19iYWxhbmNlX21vZGVsLnNob3cob3V0cGF0aD1vcy5wYXRoLmpvaW4oYmFzZV9wYXRoLCAicGxvdHMvaW1iYWxhbmNlLnBuZyIpKQogICAgY29udGV4dC5sb2dfYXJ0aWZhY3QoUGxvdEFydGlmYWN0KCJpbWJhbGFuY2UiLCBib2R5PXBsdC5nY2YoKSksIGxvY2FsX3BhdGg9InBsb3RzL2ltYmFsYW5jZS5odG1sIikKICAgIAogICAgIyBwbG90IGZlYXR1cmUgY29ycmVsYXRpb24KICAgIF9nY2ZfY2xlYXIocGx0KQogICAgdGJsY29yciA9IHRhYmxlLmNvcnIoKQogICAgYXggPSBwbHQuYXhlcygpCiAgICBzbnMuaGVhdG1hcCh0Ymxjb3JyLCBheD1heCwgYW5ub3Q9RmFsc2UsIGNtYXA9cGx0LmNtLlJlZHMpCiAgICBheC5zZXRfdGl0bGUoImZlYXR1cmVzIGNvcnJlbGF0aW9uIikKICAgIHBsdC5zYXZlZmlnKG9zLnBhdGguam9pbihiYXNlX3BhdGgsICJwbG90cy9jb3JyLnBuZyIpKQogICAgY29udGV4dC5sb2dfYXJ0aWZhY3QoUGxvdEFydGlmYWN0KCJjb3JyZWxhdGlvbiIsICBib2R5PXBsdC5nY2YoKSksIGxvY2FsX3BhdGg9InBsb3RzL2NvcnIuaHRtbCIpCiAgICAKICAgICMgcGxvdCBoaXN0b2dyYW0KICAgIF9nY2ZfY2xlYXIocGx0KQogICAgYXggPSBwbHQuYXhlcygpCiAgICBheC5zZXRfeXRpY2tsYWJlbHMoW10pCiAgICBheC5zZXRfeHRpY2tsYWJlbHMoW10pCiAgICBmaWdhcnJheSA9IHRhYmxlLmhpc3QoYXg9YXgsIHlsYWJlbHNpemU9NSwgeGxhYmVsc2l6ZT01KQogICAgZm9yIHJvdyBpbiBmaWdhcnJheToKICAgICAgICBmb3IgZiBpbiByb3c6CiAgICAgICAgICAgIGYuc2V0X3RpdGxlKCIiKQogICAgYXguc2V0X3RpdGxlKCJmZWF0dXJlcyBoaXN0b2dyYW0iKQogICAgcGx0LnNhdmVmaWcob3MucGF0aC5qb2luKGJhc2VfcGF0aCwgInBsb3RzL2hpc3QucG5nIikpCiAgICBjb250ZXh0LmxvZ19hcnRpZmFjdChQbG90QXJ0aWZhY3QoImhpc3RvZ3JhbXMiLCAgYm9keT1wbHQuZ2NmKCkpLCBsb2NhbF9wYXRoPSJwbG90cy9oaXN0Lmh0bWwiKQogICAKICAgIF9nY2ZfY2xlYXIocGx0KQo=
        source: ./
        commands: []
        code_origin: http://github.com/zilbermanor/demo-network-operations#0b8008a76e97b7806250ecf029094b597dd94507
workflows: []
