name: network-operations
functions:
- url: notebooks/generator.ipynb
  name: generator
- url: hub://aggregate:development
  name: aggregate
- url: hub://describe:master
  name: describe
- url: hub://sklearn_classifier:master
  name: train
- url: hub://test_classifier:master
  name: test
- url: notebooks/model-server.ipynb
  name: serving
workflows:
- name: main
  path: /User/demo-network-operations/src/workflow.py
artifacts:
- key: metrics
  kind: ''
  iter: 0
  tree: c57099046989eb065ee1f94445dd69d333bc1137
  target_path: /User/demo-network-operations/data/metrics.parquet
  db_key: metrics
- key: lgb_configs
  kind: ''
  iter: 0
  tree: c57099046989eb065ee1f94445dd69d333bc1137
  target_path: /User/demo-network-operations/data/lgb_model.json
  db_key: lgb_configs
