name: network-operations
functions:
- url: hub://aggregate
  name: aggregate
- url: hub://describe
  name: describe
- url: hub://feature_selection
  name: feature_selection
- url: hub://sklearn_classifier
  name: train
- url: hub://test_classifier
  name: test
- url: hub://model_server
  name: serving
- url: hub://model_server_tester
  name: model_server-tester
- url: hub://concept_drift
  name: concept_drift
- url: hub://stream_to_parquet
  name: s2p
- url: hub://virtual_drift
  name: virtual_drift
workflows:
- name: main
  path: /User/demo-network-operations/src/workflow.py
artifacts: []
