name: network-operations
functions:
- url: notebooks/generator.ipynb
  name: generator
- url: hub://aggregate:development
  name: aggregate
- url: hub://describe:master
  name: describe
- url: hub://sklearn_classifier:development
  name: train
- url: hub://test_classifier:master
  name: test
- url: notebooks/model-server.ipynb
  name: serving
workflows:
- name: main
  path: /User/demo-network-operations/src/workflow.py
artifacts:
- key: metrics
  kind: ''
  iter: 0
  tree: 43ee819b83829c4d199895e0266d6bae2829a1ed
  target_path: /User/demo-network-operations/data/metrics.parquet
  db_key: metrics
- key: lgb_configs
  kind: ''
  iter: 0
  tree: 43ee819b83829c4d199895e0266d6bae2829a1ed
  target_path: /User/demo-network-operations/data/lgb_model.json
  db_key: lgb_configs
